import { DM_Sans } from "next/font/google";
import {NotificationProvider} from '../../contexts/NotificationContext';
import {NotificationContainer} from '../../components/NotificationContainer';
import {NotificationHandler} from '../../components/NotificationHandler';
import "./globals.css";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Nexus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased bg-[#171717]`}>
      <NotificationProvider>
        {children}
        <NotificationContainer/>
        <NotificationHandler/>
        </NotificationProvider>
        </body>
    </html>
  );
}